"use client";

import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useSyncExternalStore,
  type ReactNode,
} from "react";

export type Language = "id" | "en";

const translations = {
  id: {
    "nav.mainAria": "Navigasi utama",
    "nav.homeAria": "Kembali ke awal",
    "nav.story": "Cerita kami",
    "nav.details": "Perayaan",
    "nav.rsvp": "RSVP",
    "nav.explore": "Jelajahi",
    "hero.kicker": "Kami sedang menikah",
    "hero.location": "Jakarta, Indonesia • Satu hari untuk merayakan cerita kami",
    "hero.quote": "Ke mana kamu pergi, aku akan pergi, dan di mana kamu tinggal, aku akan tinggal.",
    "hero.quoteSource": "Rut 1:16—17",
    "hero.begin": "Mulai cerita",
    "couple.eyebrow": "01 / Pasangan",
    "couple.titleTop": "Dua hati,",
    "couple.titleBottom": "satu cerita.",
    "couple.intro": "Kami adalah dua orang yang jatuh cinta pada momen-momen kecil, lalu memilih untuk merayakan setiap langkah bersama.",
    "couple.groom": "Pengantin pria",
    "couple.bride": "Pengantin wanita",
    "couple.sonOf": "Putra dari Mr. & Mrs. Suharja.",
    "couple.daughterOf": "Putri dari Mr. & Mrs. Hartono",
    "couple.together": "Bersama keluarga kami",
    "couple.readStory": "Baca cerita kami",
    "couple.instagramAria": "Instagram",
    "event.eyebrow": "02 / Perayaan",
    "event.titleTop": "Catat tanggalnya,",
    "event.titleBottom": "rayakan bersamanya.",
    "event.intro": "Kami menanti Anda menjadi bagian dari hari yang penuh hangat, tawa, dan cerita baru.",
    "event.countdown": "Hitung mundur",
    "event.heading": "Menuju hari kami",
    "event.days": "Hari",
    "event.hours": "Jam",
    "event.minutes": "Menit",
    "event.seconds": "Detik",
    "event.addCalendar": "Tambahkan ke Google Calendar",
    "event.holyMatrimony": "Sakramen Pernikahan",
    "event.reception": "Resepsi Pernikahan",
    "event.date": "Sabtu, 6 Maret 2027",
    "event.calendarDetails": "Bergabunglah bersama kami merayakan cinta Jonathan dan Georgia.",
    "event.findWay": "Temukan lokasi",
    "event.openMaps": "Buka di Google Maps",
    "event.attire": "Panduan pakaian",
    "event.gardenFormal": "Garden formal",
    "event.colorLabel": "Pilihan warna pakaian",
    "event.attireDesc": "Warna earth tone pilihan kami untuk hari yang hangat.",
    "event.gift": "Hadiah pernikahan",
    "event.giftTitle": "Kirim hadiah",
    "event.bank": "BCA · a.n. Gabriel & Yunita.",
    "event.copyNumber": "Salin nomor rekening",
    "event.copied": "Nomor tersalin",
    "event.liveStream": "Live streaming",
    "event.joinRemote": "Ikuti dari jarak jauh",
    "event.streamDesc": "Tautan broadcast akan dibagikan menjelang hari acara.",
    "event.comingSoon": "Segera hadir",
    "story.eyebrow": "03 / Perjalanan cinta",
    "story.titleTop": "Cinta, dalam",
    "story.titleBottom": "setiap bab.",
    "story.since": "Sejak 2019",
    "story.firstTitle": "Pertemuan pertama",
    "story.firstText": "Di sebuah kedai kopi kecil, kami menemukan bahwa obrolan yang ringan dapat menjadi awal cerita yang panjang.",
    "story.secondTitle": "Berdua",
    "story.secondText": "Berbagi tawa, cerita, dan banyak perjalanan kecil. Setiap petualangan membuat kami semakin yakin memilih satu sama lain.",
    "story.thirdTitle": "Perjalanan baru",
    "story.thirdText": "Kini kami siap menulis bab baru: hidup berdua, berbagi semangat, dan merayakan cinta bersama keluarga.",
    "story.bestYet": "Yang terbaik masih akan datang.",
    "story.seeMore": "Lihat lebih banyak",
    "gallery.eyebrow": "04 / Potret kami",
    "gallery.titleTop": "Momen yang",
    "gallery.titleBottom": "kami simpan dekat.",
    "gallery.selected": "Frame pilihan",
    "gallery.labelOne": "Sejenis keabadian yang tenang",
    "gallery.labelTwo": "Berpakaian dalam kegembiraan",
    "gallery.labelThree": "Detail-detail kecil",
    "gallery.more": "Lebih banyak kenangan segera hadir",
    "rsvp.eyebrow": "05 / Simpan tempat Anda",
    "rsvp.titleTop": "Apakah Anda",
    "rsvp.titleBottom": "akan hadir?",
    "rsvp.intro": "Kehadiran Anda sangat berarti bagi kami. Mohon isi formulir ini agar kami dapat menyiapkan tempat yang terbaik untuk Anda.",
    "rsvp.deadline": "Batas hingga 15 Agustus 2026",
    "rsvp.form": "Formulir RSVP",
    "rsvp.counting": "Kami menghitung presence Anda",
    "rsvp.fullName": "Nama lengkap",
    "rsvp.namePlaceholder": "Tulis nama Anda",
    "rsvp.address": "Alamat / kota",
    "rsvp.optional": "(opsional)",
    "rsvp.cityPlaceholder": "Dari kota mana Anda datang?",
    "rsvp.confirmation": "Konfirmasi kehadiran",
    "rsvp.attending": "Saya hadir",
    "rsvp.attendingDesc": "Saya tidak akan melewatkan hari besar ini.",
    "rsvp.notAttending": "Maaf, tidak hadir",
    "rsvp.notAttendingDesc": "Doakan saya dari jauh.",
    "rsvp.guests": "Jumlah tamu",
    "rsvp.guestCount": "{count} orang",
    "rsvp.sending": "Mengirim konfirmasi",
    "rsvp.send": "Kirim konfirmasi",
    "rsvp.inactive": "RSVP belum aktif. Hubungi kami jika Anda membutuhkan bantuan.",
    "rsvp.error": "Gagal mengirim konfirmasi. Silakan coba beberapa saat lagi.",
    "rsvp.success": "Terima kasih! Konfirmasi kehadiran Anda telah kami terima.",
    "wishes.eyebrow": "06 / Buku tamu digital",
    "wishes.titleTop": "Tinggalkan sedikit",
    "wishes.titleBottom": "cinta di sini.",
    "wishes.empty": "Jadilah orang pertama yang meninggalkan ucapan.",
    "wishes.write": "Tulis ucapan",
    "wishes.wordsMatter": "Kata-kata Anda berarti",
    "wishes.live": "Live",
    "wishes.preview": "Pratinjau",
    "wishes.name": "Nama Anda",
    "wishes.namePlaceholder": "Nama atau nama keluarga",
    "wishes.message": "Ucapan",
    "wishes.messagePlaceholder": "Tulis pesan untuk pasangan pengantin",
    "wishes.sending": "Mengirim",
    "wishes.send": "Kirim ucapan",
    "wishes.localStatus": "Ucapan tersimpan di perangkat ini. Terima kasih!",
    "wishes.error": "Gagal mengirim ucapan. Silakan coba lagi.",
    "wishes.success": "Ucapan Anda sudah tiba di buku tamu kami.",
    "wishes.footer": "Ucapan akan tampil langsung di buku tamu digital kami.",
    "wishes.sampleOne": "Semoga hari-hari kalian penuh cinta, tawa, dan kenangan indah.",
    "wishes.sampleTwo": "Sangat bahagia untuk kalian berdua. Semoga hari-hari terindah menunggu kalian.",
    "wishes.sampleThree": "Semoga cinta kalian terus bertumbuh, hari demi hari.",
    "closing.eyebrow": "07 / Sampai jumpa lagi",
    "closing.titleTop": "Sampai",
    "closing.titleBottom": "jumpa.",
    "closing.text": "Terima kasih sudah menjadi bagian dari cerita kami. Sampai jumpa di hari yang kami nanti-nantikan bersama keluarga dan teman-teman tercinta.",
    "closing.rsvp": "Konfirmasi kehadiran",
    "closing.checkin": "Lokasi check-in",
    "closing.venue": "The Pearl Hotel",
    "closing.scan": "Pindai QR code ini saat tiba untuk membuka lokasi acara.",
    "closing.openMaps": "Buka peta",
    "closing.made": "Dibuat dengan cinta untuk orang-orang tercinta",
    "closing.back": "Kembali ke atas",
    "closing.forever": "Abadi dimulai di sini",
    "language.label": "Pilih bahasa",
    "language.switchToEn": "Ganti ke English",
    "language.switchToId": "Ganti ke Bahasa Indonesia",
    "audio.play": "Putar musik",
    "audio.pause": "Jeda musik",
    "audio.musicOn": "Musik aktif",
  },
  en: {
    "nav.mainAria": "Main navigation",
    "nav.homeAria": "Back to top",
    "nav.story": "Our story",
    "nav.details": "The celebration",
    "nav.rsvp": "RSVP",
    "nav.explore": "Explore",
    "hero.kicker": "We are getting married",
    "hero.location": "Jakarta, Indonesia • One day to celebrate our story",
    "hero.quote": "Where you go I will go, and where you stay I will stay.",
    "hero.quoteSource": "Ruth 1:16—17",
    "hero.begin": "Begin the story",
    "couple.eyebrow": "01 / The couple",
    "couple.titleTop": "Two hearts,",
    "couple.titleBottom": "one story.",
    "couple.intro": "We are two people who fell in love with the little moments, then chose to celebrate every step together.",
    "couple.groom": "The Groom",
    "couple.bride": "The Bride",
    "couple.sonOf": "Son of Mr. & Mrs. Suharja.",
    "couple.daughterOf": "Daughter of Mr. & Mrs. Hartono",
    "couple.together": "Together with their families",
    "couple.readStory": "Read our story",
    "couple.instagramAria": "Instagram",
    "event.eyebrow": "02 / The celebration",
    "event.titleTop": "Save the date,",
    "event.titleBottom": "join the joy.",
    "event.intro": "We look forward to having you be part of a day filled with warmth, laughter, and new stories.",
    "event.countdown": "The countdown",
    "event.heading": "Heading towards our day",
    "event.days": "Days",
    "event.hours": "Hours",
    "event.minutes": "Mins",
    "event.seconds": "Secs",
    "event.addCalendar": "Add to Google Calendar",
    "event.holyMatrimony": "Holy Matrimony",
    "event.reception": "Wedding Reception",
    "event.date": "Saturday, 6 March 2027",
    "event.calendarDetails": "Join us as we celebrate Jonathan and Georgia's love.",
    "event.findWay": "Find your way",
    "event.openMaps": "Open in Google Maps",
    "event.attire": "Attire guide",
    "event.gardenFormal": "Garden formal",
    "event.colorLabel": "Attire color choices",
    "event.attireDesc": "Our go-to earth tones for warm days.",
    "event.gift": "Wedding gift",
    "event.giftTitle": "Send a gift",
    "event.bank": "BCA · a.n. Gabriel & Yunita.",
    "event.copyNumber": "Copy account number",
    "event.copied": "Number copied",
    "event.liveStream": "Live stream",
    "event.joinRemote": "Join remotely",
    "event.streamDesc": "The broadcast link will be shared closer to the event date.",
    "event.comingSoon": "Coming soon",
    "story.eyebrow": "03 / The love journey",
    "story.titleTop": "Love, in",
    "story.titleBottom": "every chapter.",
    "story.since": "Since 2019",
    "story.firstTitle": "First meeting",
    "story.firstText": "In a small coffee shop, we discovered that a simple conversation can become the beginning of a long story.",
    "story.secondTitle": "Two become one",
    "story.secondText": "Sharing laughter, stories, and little journeys. Every adventure makes us more certain that we choose each other.",
    "story.thirdText": "Now we are ready to write a new chapter: building a life together, sharing our spirit, and celebrating love with family.",
    "story.thirdTitle": "New journey",
    "story.bestYet": "The best is yet to come.",
    "story.seeMore": "See more of us",
    "gallery.eyebrow": "04 / Portrait of us",
    "gallery.titleTop": "Moments we",
    "gallery.titleBottom": "keep close.",
    "gallery.selected": "Selected frames",
    "gallery.labelOne": "A quiet kind of forever",
    "gallery.labelTwo": "Dressed in a little joy",
    "gallery.labelThree": "The little details",
    "gallery.more": "More memories loading soon",
    "rsvp.eyebrow": "05 / Save your seat",
    "rsvp.titleTop": "Will you",
    "rsvp.titleBottom": "join us?",
    "rsvp.intro": "Your presence means so much to us. Please fill out this form so we can prepare the best seat for you.",
    "rsvp.deadline": "Kindly respond by 15 August 2026",
    "rsvp.form": "RSVP form",
    "rsvp.counting": "We are counting on you",
    "rsvp.fullName": "Full name",
    "rsvp.namePlaceholder": "Write your name",
    "rsvp.address": "Address / city",
    "rsvp.optional": "(optional)",
    "rsvp.cityPlaceholder": "Which city are you coming from?",
    "rsvp.confirmation": "Attendance confirmation",
    "rsvp.attending": "I will attend",
    "rsvp.attendingDesc": "I would not miss this special day.",
    "rsvp.notAttending": "Sorry, I cannot attend",
    "rsvp.notAttendingDesc": "Please send your wishes from afar.",
    "rsvp.guests": "Number of guests",
    "rsvp.guestCount": "{count} people",
    "rsvp.sending": "Sending confirmation",
    "rsvp.send": "Send confirmation",
    "rsvp.inactive": "RSVP is not active yet. Please contact us if you need help.",
    "rsvp.error": "We could not send your confirmation. Please try again in a moment.",
    "rsvp.success": "Thank you! Your attendance confirmation has been received.",
    "wishes.eyebrow": "06 / Digital guestbook",
    "wishes.titleTop": "Leave a little",
    "wishes.titleBottom": "love behind.",
    "wishes.empty": "Be the first to leave a wish.",
    "wishes.write": "Write a wish",
    "wishes.wordsMatter": "Your words matter",
    "wishes.live": "Live",
    "wishes.preview": "Preview",
    "wishes.name": "Your name",
    "wishes.namePlaceholder": "Name or family name",
    "wishes.message": "Your wish",
    "wishes.messagePlaceholder": "Write a message for the couple",
    "wishes.sending": "Sending",
    "wishes.send": "Send a wish",
    "wishes.localStatus": "Your wish is saved on this device. Thank you!",
    "wishes.error": "We could not send your wish. Please try again.",
    "wishes.success": "Your wish has arrived in our guestbook.",
    "wishes.footer": "Your wish will appear instantly in our digital guestbook.",
    "wishes.sampleOne": "Wishing you a lifetime of love, laughter, and beautiful memories.",
    "wishes.sampleTwo": "So happy for you both. May your happiest days be ahead.",
    "wishes.sampleThree": "May your love keep growing, one beautiful day at a time.",
    "closing.eyebrow": "07 / Until we meet again",
    "closing.titleTop": "See you",
    "closing.titleBottom": "there.",
    "closing.text": "Thank you for being part of our story. See you on the day we have been looking forward to with the people we love most.",
    "closing.rsvp": "Confirm your attendance",
    "closing.checkin": "Check-in location",
    "closing.venue": "The Pearl Hotel",
    "closing.scan": "Scan this QR code when you arrive to open the event location.",
    "closing.openMaps": "Open maps",
    "closing.made": "Made with love for our favorite people",
    "closing.back": "Back to top",
    "closing.forever": "Forever starts here",
    "language.label": "Choose language",
    "language.switchToEn": "Switch to English",
    "language.switchToId": "Switch to Indonesian",
    "audio.play": "Play music",
    "audio.pause": "Pause music",
    "audio.musicOn": "Music on",
  },
} as const;

export type TranslationKey = keyof typeof translations.id;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: TranslationKey) => string;
};

const LANGUAGE_STORAGE_KEY = "wedding-language";
const LANGUAGE_CHANGE_EVENT = "wedding-language-change";

const getLanguageSnapshot = (): Language => {
  if (typeof window === "undefined") return "id";
  const savedLanguage = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
  return savedLanguage === "en" ? "en" : "id";
};

const getServerLanguage = (): Language => "id";

const subscribeToLanguage = (onStoreChange: () => void) => {
  const handleChange = () => onStoreChange();
  window.addEventListener("storage", handleChange);
  window.addEventListener(LANGUAGE_CHANGE_EVENT, handleChange);
  return () => {
    window.removeEventListener("storage", handleChange);
    window.removeEventListener(LANGUAGE_CHANGE_EVENT, handleChange);
  };
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: Readonly<{ children: ReactNode }>) {
  const language = useSyncExternalStore(subscribeToLanguage, getLanguageSnapshot, getServerLanguage);
  const setLanguage = useCallback((nextLanguage: Language) => {
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, nextLanguage);
    window.dispatchEvent(new Event(LANGUAGE_CHANGE_EVENT));
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage,
      t: (key) => translations[language][key],
    }),
    [language, setLanguage],
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
}
